apiVersion: apps/v1
kind: Deployment
metadata:
  name: carapi-deployment
  labels:
    app: carapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carapi
  template:
    metadata:
      labels:
        app: carapi
    spec:
      containers:
        - name: carapi
          image: localhost:32000/carapi
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: carapi-service
  labels:
    service: carapi
spec:
  selector:
    app: carapi
  type: ClusterIP
  ports:
  - port: 6060
    targetPort: 6000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carapi
spec:
  defaultBackend:
    service:
      name: carapi-service
      port:
        number: 6060
